# -*- coding: utf-8 -*-
# Вопросы и ответы для блока «Частые вопросы». Только факты, которые уже есть на сайте.
FAQ = {
'index.html': [
 ('Чем занимается MakeBiz Group?',
  'MakeBiz Group, юридически MakeBiz Technologies FZE LLC, это IT-компания в ОАЭ. Мы внедряем CRM Битрикс24, AI-агентов, речевую аналитику звонков Vector, AI-обработку документов IntDoc, BI-аналитику и серверы. 8 лет на рынке IT и AI, более 150 проектов внедрения.'),
 ('Сколько стоит внедрение и от чего зависит цена?',
  'Стандартная настройка Битрикс24 от 10 000 AED, команда AI-агентов от 6 000 AED, речевая аналитика Vector от 1 000 AED в месяц. Цена зависит от числа процессов, интеграций и объёма данных. Смету в дирхамах фиксируем до начала работ.'),
 ('Как проходит работа над проектом?',
  'Четыре шага: разбираем текущие процессы и считаем потери, собираем архитектуру решения и даём смету, внедряем и обучаем команду, дальше сопровождаем и развиваем систему. Поддержка работает 24/7.'),
 ('Работаете только в ОАЭ?',
  'Основной офис в ОАЭ, работаем с бизнесом в Дубае и по эмиратам, а также с русскоязычными компаниями по всему миру. Встречи проводим онлайн в Zoom или лично в Дубае, на русском и английском.'),
 ('На чьей инфраструктуре работает решение?',
  'На вашей. Битрикс24 можно поставить коробочный на ваш сервер, AI-агенты разворачиваются на вашем сервере, аккаунты и доступы остаются у вас.'),
],
'bitrix.html': [
 ('Сколько стоит внедрение Битрикс24 в Дубае и ОАЭ?',
  'Стандартная настройка CRM от 10 000 AED. Сопровождение пакетами часов: 5 часов в месяц 1 250 AED, 10 часов 2 300 AED, 20 часов 4 200 AED.'),
 ('Что входит во внедрение?',
  'CRM и карточки клиентов, воронки продаж, телефония, автоматизация рутинных действий, отчёты и BI, интеграции с сайтом, мессенджерами и вашими системами.'),
 ('Облачный Битрикс24 или коробочный на своём сервере?',
  'Работаем с обоими. Коробочную версию ставим на ваш сервер и дорабатываем под процессы, так сделано в проектах Unilin и СДЭК.'),
 ('Переносите ли данные из другой CRM?',
  'Да, переносим клиентов, сделки и историю из текущей системы или таблиц, чтобы работа не начиналась с пустой базы.'),
 ('Что будет после запуска?',
  'Обучаем команду и остаёмся на поддержке пакетами часов, дорабатываем систему по мере роста компании.'),
],
'ai-agents.html': [
 ('Что такое AI-агент и чем он отличается от чат-бота?',
  'Чат-бот отвечает на вопрос и забывает его. У агента есть роль, память и доступ к вашим системам: он ведёт процесс сам и доводит его до результата.'),
 ('Сколько стоит команда AI-агентов?',
  'Внедрение от 6 000 AED. Тарифы: Старт 6 000 AED, Бизнес 11 000 AED, Холдинг 25 000 AED разово, обслуживание 10% от стоимости внедрения в месяц. Собрать состав и увидеть цену можно в калькуляторе.'),
 ('Где работают агенты?',
  'В Telegram и в вашей CRM. Агенты разворачиваются на сервере клиента и имеют общую память и доступ к нужным системам.'),
 ('Какие процессы обычно отдают агентам?',
  'Продажи и квалификацию заявок, подготовку документов и КП, разбор звонков, отчётность. В каталоге 77 агентов по 9 направлениям.'),
 ('Данные останутся у нас?',
  'Да. Система работает на вашем сервере и в ваших аккаунтах, доступы остаются у вас.'),
],
'vector.html': [
 ('Что делает Vector?',
  'Vector слушает 100% звонков отдела продаж, а не выборку, разбирает разговор по 10 этапам и показывает, на каком шаге теряется клиент.'),
 ('Сколько стоит Vector?',
  'Старт 1 000 AED в месяц за 5 000 минут, Команда 1 700 AED за 10 000 минут, Масштаб от 4 000 AED от 30 000 минут. При предоплате действуют скидки до 20%.'),
 ('Нужно ли менять телефонию?',
  'Нет. Vector подключается к текущей телефонии и CRM, менять номер и оператора не нужно.'),
 ('Что получает руководитель?',
  'Оценку каждого разговора по критериям качества, эскалацию при падении качества и сводные отчёты в BI. В проекте HAVAL так разбирается более 300 000 минут в месяц по 40+ критериям.'),
],
'intdoc.html': [
 ('Что делает IntDoc?',
  'IntDoc извлекает цены, сроки и наличие из коммерческих предложений, счетов, прайс-листов и сканов, сравнивает поставщиков в одной таблице и обосновывает выбор.'),
 ('Чем это отличается от обычного распознавания документов?',
  'Распознавание только вытаскивает текст. IntDoc сводит предложения разных поставщиков к общему виду и показывает, какое выгоднее по цене, сроку и наличию.'),
 ('С какими документами он работает?',
  'С КП, счетами, прайс-листами и сканами, в том числе снятыми на телефон.'),
 ('Сколько стоит?',
  'Цена зависит от объёма документов и числа поставщиков, считаем под задачу. Напишите нам, разберём ваш поток закупок.'),
],
'vps.html': [
 ('Какой сервер выбрать?',
  'Мы сравниваем семь площадок: Truehost Cloud, VPS.org, DataPacket, Hostman, UltaHost, IShosting и AEserver, и подбираем под задачу, бюджет и требования к расположению данных.'),
 ('Вы продаёте серверы?',
  'Нет. Сервер вы берёте сами и остаётесь его владельцем, а разворачиваем, настраиваем и обслуживаем его мы.'),
 ('Что входит в обслуживание?',
  'Развёртывание, настройка окружения, обновления, резервные копии и мониторинг. Поддержка работает 24/7.'),
 ('Зачем свой сервер для AI-агентов?',
  'Чтобы данные и доступы оставались внутри компании: агенты работают на вашем сервере, а не на чужой площадке.'),
],
'bitrix-support.html': [
 ('Сколько стоит техподдержка Битрикс24?',
  'Пакеты по часам в месяц: 5 часов 1 250 AED, 10 часов 2 300 AED, 20 часов 4 200 AED. Дополнительный час сверх пакета 250 AED.'),
 ('Что входит в поддержку?',
  'Администрирование пользователей и прав, корректировка настроек CRM-сущностей, правка ролей и доступов, обновление процессов и автоматизаций, настройка уведомлений, почта, телефония и мессенджеры, отчёты и консультации команды.'),
 ('Как считаются часы?',
  'Использованные часы фиксируются открыто: вы видите, на какие задачи они ушли. Час сверх пакета стоит 250 AED.'),
 ('С чего начинается сопровождение?',
  'С аудита портала: смотрим, как настроены процессы, права и интеграции, и собираем план работ по приоритету. Дальше подбираем пакет часов под объём задач.'),
],
'company.html': [
 ('Кто такие MakeBiz Group?',
  'IT-компания в ОАЭ, юридически MakeBiz Technologies FZE LLC, компания свободной экономической зоны Ajman NuVentures Centre, регистрационный номер 2624215090888. 8 лет на рынке IT и AI, более 150 проектов внедрения, поддержка 24/7.'),
 ('С какими компаниями вы работаете?',
  'Среди клиентов крупные компании из логистики, автопрома, производства, недвижимости и обучения: СДЭК, HAVAL, Unilin, Apartico, Перформия.'),
 ('На каких языках вы работаете?',
  'На русском и английском, включая документы и договоры. Встречи проводим онлайн в Zoom или лично в Дубае.'),
 ('В какой валюте вы считаете смету?',
  'В дирхамах ОАЭ. Смета фиксируется до начала работ, объём согласовывается заранее.'),
],
'bitrix-real-estate.html': [
 ('Можно ли получать заявки с Property Finder, Bayut и Dubizzle прямо в Битрикс24?',
  'Да. Заявки приходят в CRM через интеграцию портала или приложение из Битрикс24 Маркета, сразу получают ответственного брокера по району или типу объекта, а повторный клиент попадает в свою карточку.'),
 ('Как хранить номер разрешения Trakheesi?',
  'Номер разрешения и срок действия лежат в карточке объекта. До окончания срока CRM заранее напоминает брокеру и руководителю, чтобы объявление не осталось на портале с истёкшим разрешением.'),
 ('Поддерживаются ли формы RERA?',
  'Этапы сделки привязываются к формам A, B, F и I, шаблоны документов заполняются из карточки сделки.'),
 ('Сколько стоит CRM для агентства недвижимости?',
  'Стандартная настройка Битрикс24 от 10 000 AED. Точная смета зависит от числа воронок, порталов и интеграций, фиксируем её в дирхамах до начала работ.'),
],
'bitrix-whatsapp.html': [
 ('Можно ли подключить WhatsApp к Битрикс24 официально?',
  'Да, через WhatsApp Business Platform (API от Meta) и коннектор в Контакт-центре Битрикс24: Twilio, Edna или приложение из Битрикс24 Маркета. Номер компании проходит проверку Meta.'),
 ('Что такое правило 24 часов?',
  'Свободным текстом можно отвечать в течение 24 часов после последнего сообщения клиента. Когда окно закрылось, первым можно написать только шаблоном, заранее одобренным Meta.'),
 ('Сколько менеджеров могут работать с одним номером?',
  'Все. Диалоги распределяются между менеджерами через открытые линии, история остаётся в карточке клиента, даже если сотрудник уходит.'),
 ('Сколько стоит подключение WhatsApp?',
  'Подключение входит во внедрение Битрикс24 (стандартная настройка от 10 000 AED) или делается в рамках пакета поддержки. Сообщения по шаблонам оплачиваются провайдеру отдельно.'),
],
'bitrix-vat-einvoicing.html': [
 ('Когда e-invoicing в ОАЭ становится обязательным?',
  'Для компаний с выручкой от 50 млн AED с 1 января 2027 (выбрать провайдера ASP до 30 октября 2026), для остальных с 1 июля 2027 (ASP до 31 марта 2027), для государственных организаций с 1 октября 2027. С 1 июля 2026 идёт пилот и добровольный переход.'),
 ('Выставляет ли Битрикс24 электронный счёт сам?',
  'Нет. Электронный счёт формирует учётная система и передаёт через аккредитованного провайдера. Битрикс24 отвечает за чистые данные: TRN, реквизиты, товары с налогом, и передаёт сделку в учётную систему по API.'),
 ('Как настроить VAT 5% в Битрикс24?',
  'Ставка задаётся в каталоге товаров, цены можно вести с налогом или без, сумма VAT выводится отдельной строкой в сделке и в счёте.'),
 ('Можно ли вести сделки в разных валютах?',
  'Да. Базовая валюта AED, сделки можно вести в USD, EUR или рублях, отчёты сводятся в дирхамах по заданному курсу.'),
],
}

FAQ_EN = {
'en/index.html': [
 ('What does MakeBiz Group do?',
  'MakeBiz Group, legally MakeBiz Technologies FZE LLC, is an IT company in the UAE. We implement Bitrix24 CRM, AI agents, Vector speech analytics for sales calls, IntDoc document AI, BI analytics and servers. 8 years in IT and AI, over 150 implementation projects.'),
 ('How much does an implementation cost?',
  'A standard Bitrix24 setup starts at AED 10,000, a team of AI agents at AED 6,000, Vector speech analytics at AED 1,000 a month. The price depends on the number of processes, integrations and data volume. The quote in dirhams is fixed before the work starts.'),
 ('How does a project run?',
  'Four steps: we study the current processes and count the losses, design the solution and give a quote, implement it and train your team, then support and develop the system. Support runs 24/7.'),
 ('Do you work outside the UAE?',
  'Our office is in the UAE and we work with businesses in Dubai and across the emirates, as well as with Russian-speaking companies worldwide. Meetings are held over Zoom or in person in Dubai, in English or Russian.'),
 ('Whose infrastructure does the solution run on?',
  'Yours. Bitrix24 can be installed on premise on your own server, AI agents are deployed on your server, and the accounts and access stay with you.'),
],
'en/bitrix.html': [
 ('How much does Bitrix24 implementation in Dubai and the UAE cost?',
  'A standard CRM setup starts at AED 10,000. Support comes in hour packages: 5 hours a month for AED 1,250, 10 hours for AED 2,300, 20 hours for AED 4,200.'),
 ('What is included in the implementation?',
  'CRM and client records, sales pipelines, telephony, automation of routine actions, reports and BI, and integrations with your website, messengers and internal systems.'),
 ('Cloud Bitrix24 or on premise?',
  'Both. We install the on premise edition on your own server and customize it around your processes, as we did for Unilin and CDEK.'),
 ('Do you migrate data from another CRM?',
  'Yes. We migrate clients, deals and history from your current system or spreadsheets so the team does not start from an empty database.'),
 ('What happens after launch?',
  'We train the team and stay on support with hour packages, extending the system as the company grows.'),
],
'en/ai-agents.html': [
 ('What is an AI agent and how is it different from a chatbot?',
  'A chatbot answers a question and forgets it. An agent has a role, memory and access to your systems: it runs the process itself and sees it through to a result.'),
 ('How much does a team of AI agents cost?',
  'Implementation starts at AED 6,000. Plans: Start AED 6,000, Business AED 11,000, Holding AED 25,000 one off, with maintenance at 10% of the implementation price per month.'),
 ('Where do the agents work?',
  'In Telegram and inside your CRM. Agents are deployed on the client server and share memory and access to the systems they need.'),
 ('Which processes are usually handed to agents?',
  'Sales and lead qualification, preparing documents and quotes, reviewing calls, and reporting. The catalogue holds 77 agents across 9 areas.'),
 ('Does our data stay with us?',
  'Yes. The system runs on your server and in your accounts, and the access stays with you.'),
],
'en/vector.html': [
 ('What does Vector do?',
  'Vector listens to 100% of sales calls rather than a sample, scores the conversation against all 10 stages and shows at which step the client is lost.'),
 ('How much does Vector cost?',
  'Start is AED 1,000 a month for 5,000 minutes, Team AED 1,700 for 10,000 minutes, Scale from AED 4,000 for 30,000 minutes and up. Prepayment discounts go up to 20%.'),
 ('Do we need to change our telephony?',
  'No. Vector connects to your current telephony and CRM, so there is no need to change the number or the provider.'),
 ('What does a manager get out of it?',
  'A score for every conversation, escalation when quality drops, and roll up reports in BI. On the HAVAL project this covers over 300,000 minutes a month against 40+ criteria.'),
],
'en/intdoc.html': [
 ('What does IntDoc do?',
  'IntDoc extracts prices, lead times and availability from quotes, invoices, price lists and scans, compares suppliers in one table and justifies the choice.'),
 ('How is this different from ordinary document recognition?',
  'Recognition only pulls out the text. IntDoc brings offers from different suppliers to a common shape and shows which one wins on price, lead time and availability.'),
 ('Which documents does it handle?',
  'Quotes, invoices, price lists and scans, including photos taken on a phone.'),
 ('How much does it cost?',
  'The price depends on the volume of documents and the number of suppliers, so we quote per case. Write to us and we will look at your procurement flow.'),
],
'en/vps.html': [
 ('Which server should we choose?',
  'We compare seven providers: Truehost Cloud, VPS.org, DataPacket, Hostman, UltaHost, IShosting and AEserver, and pick one to match the workload, the budget and your data location requirements.'),
 ('Do you sell servers?',
  'No. You buy the server and stay its owner, while we deploy, configure and maintain it.'),
 ('What does maintenance include?',
  'Deployment, environment setup, updates, backups and monitoring. Support runs 24/7.'),
 ('Why do AI agents need our own server?',
  'So the data and the access stay inside the company: the agents run on your server rather than on someone else platform.'),
],
'en/bitrix-support.html': [
 ('How much does Bitrix24 support cost?',
  'Packages by hours per month: 5 hours AED 1,250, 10 hours AED 2,300, 20 hours AED 4,200. An extra hour beyond the package costs AED 250.'),
 ('What does support include?',
  'User and permission administration, adjustment of CRM entity settings, editing roles and access logic, updating processes and automations, notifications, email, telephony and messengers, reports and consultations for your team.'),
 ('How are the hours counted?',
  'Used hours are logged openly, so you can see which tasks they went to. An hour beyond the package costs AED 250.'),
 ('How does the work start?',
  'With a portal audit: we review how processes, permissions and integrations are set up and build a prioritized plan. Then we pick the package of hours to match the workload.'),
],
'en/company.html': [
 ('Who is MakeBiz Group?',
  'An IT company in the UAE, legally MakeBiz Technologies FZE LLC, a free zone company of Ajman NuVentures Centre, registration number 2624215090888. 8 years in IT and AI, over 150 implementation projects, 24/7 support.'),
 ('What kind of companies do you work with?',
  'Our clients include large companies in logistics, automotive, manufacturing, real estate and education: CDEK, HAVAL, Unilin, Apartico and Performia.'),
 ('Which languages do you work in?',
  'English and Russian, including documents and contracts. Meetings are held over Zoom or in person in Dubai.'),
 ('Which currency do you quote in?',
  'In UAE dirhams. The quote is fixed before the work starts and the scope is agreed in advance.'),
],
'en/bitrix-real-estate.html': [
 ('Can Property Finder, Bayut and Dubizzle leads go straight into Bitrix24?',
  'Yes. Leads reach the CRM through the portal integration or an app from the Bitrix24 Market, get a broker assigned by community or property type right away, and a returning client goes to their existing record.'),
 ('Where is the Trakheesi permit number kept?',
  'The permit number and expiry date sit in the property record. Before the permit expires the CRM reminds the broker and the manager, so a listing does not stay on a portal with an expired permit.'),
 ('Are RERA forms supported?',
  'Deal stages are tied to Forms A, B, F and I, and document templates fill in from the deal record.'),
 ('How much does a real estate CRM cost?',
  'Standard Bitrix24 setup starts from AED 10,000. The exact quote depends on the number of pipelines, portals and integrations and is fixed in dirhams before the work starts.'),
],
'en/bitrix-whatsapp.html': [
 ('Can WhatsApp be connected to Bitrix24 officially?',
  "Yes, through the WhatsApp Business Platform (Meta's API) and a connector in the Bitrix24 Contact Center: Twilio, Edna or an app from the Bitrix24 Market. The company number goes through Meta verification."),
 ('What is the 24-hour rule?',
  "You can reply in free text within 24 hours of the client's last message. Once the window closes, you can only write first with a template approved by Meta."),
 ('How many managers can work with one number?',
  'All of them. Chats are distributed through Open Channels and the history stays in the client record even when an employee leaves.'),
 ('How much does the WhatsApp connection cost?',
  'It is part of a Bitrix24 implementation (standard setup from AED 10,000) or done within a support package. Template messages are paid to the provider separately.'),
],
'en/bitrix-vat-einvoicing.html': [
 ('When does e-invoicing become mandatory in the UAE?',
  'For businesses with revenue of AED 50 million or more from 1 January 2027 (appoint an ASP by 30 October 2026), for everyone else from 1 July 2027 (ASP by 31 March 2027), for government entities from 1 October 2027. A pilot and voluntary adoption run from 1 July 2026.'),
 ('Does Bitrix24 issue the electronic invoice itself?',
  'No. The electronic invoice is produced by the accounting system and sent through an accredited service provider. Bitrix24 keeps the data clean: TRN, client details, products with tax, and passes the deal to the accounting system by API.'),
 ('How is 5% VAT set up in Bitrix24?',
  'The rate is set in the product catalogue, prices can include or exclude tax, and the VAT amount appears as a separate line in the deal and the invoice.'),
 ('Can deals be run in different currencies?',
  'Yes. AED is the base currency, deals can be in USD, EUR or roubles, and reports roll up in dirhams at the rate you set.'),
],
}
