# Заголовки и описания страниц (RU/EN). Длина title <= 65, description 120-160
META = {
 'index.html': ('Внедрение AI и CRM Битрикс24 в Дубае и ОАЭ | MakeBiz Group',
   'IT-компания в ОАЭ: внедряем AI-агентов, CRM Битрикс24, речевую аналитику звонков и BI. Находим, где бизнес теряет деньги, и автоматизируем продажи и документы.'),
 'en/index.html': ('AI, Bitrix24 CRM and business automation in Dubai | MakeBiz',
   'UAE IT company: we implement AI agents, Bitrix24 CRM, call speech analytics and BI. We find where your business loses money and automate sales and documents.'),
 'bitrix.html': ('Внедрение Битрикс24 в Дубае и ОАЭ под ключ | MakeBiz Group',
   'Внедрение и настройка Битрикс24 в Дубае и ОАЭ: CRM, воронки, телефония, автоматизация, BI и интеграции. Настройка от 10 000 AED, сопровождение от 1 250 AED.'),
 'en/bitrix.html': ('Bitrix24 implementation in Dubai and the UAE | MakeBiz Group',
   'Bitrix24 setup in Dubai and the UAE: CRM, sales pipelines, telephony, automation, BI and integrations. Setup from AED 10,000, support from AED 1,250 a month.'),
 'ai-agents.html': ('AI-агенты для бизнеса в Дубае и ОАЭ под ключ | MakeBiz Group',
   'ИИ-агенты под ключ: команда AI-сотрудников ведёт продажи, документы, звонки и отчёты в Telegram и вашей CRM. Покажем систему на вашем процессе. От 6 000 AED.'),
 'en/ai-agents.html': ('AI agents for business in Dubai and the UAE | MakeBiz Group',
   'Turnkey AI agents: a team of AI employees runs sales, documents, calls and reports in Telegram and your CRM. See it live on your process. From AED 6,000.'),
 'vector.html': ('Vector: речевая аналитика звонков на базе AI | MakeBiz Group',
   'Vector слушает 100% звонков, оценивает 10 этапов разговора и показывает, где отдел продаж теряет клиентов. Тарифы от 1 000 AED в месяц, без смены телефонии.'),
 'en/vector.html': ('Vector: AI speech analytics for sales calls | MakeBiz Group',
   'Vector listens to 100% of sales calls, scores all 10 conversation stages and shows where clients are lost. Plans from AED 1,000 a month, no telephony change.'),
 'intdoc.html': ('IntDoc: AI-сравнение поставщиков по документам | MakeBiz Group',
   'IntDoc извлекает цены, сроки и наличие из КП, счетов, прайсов и сканов, сравнивает поставщиков в одной таблице и обосновывает выбор. Без ручной работы в Excel.'),
 'en/intdoc.html': ('IntDoc: AI supplier comparison from any documents | MakeBiz',
   'IntDoc extracts prices, lead times and availability from quotes, invoices, price lists and scans, compares suppliers in one table and justifies the choice.'),
 'vps.html': ('Серверы и VPS в ОАЭ и мире: подбор и настройка | MakeBiz Group',
   'Сравните 7 площадок: Truehost Cloud, VPS.org, DataPacket, Hostman, UltaHost, IShosting и AEserver. Сервер берёте сами, а развернём и обслужим его мы.'),
 'en/vps.html': ('Servers and VPS in the UAE and worldwide, set up by MakeBiz',
   'Compare 7 providers: Truehost Cloud, VPS.org, DataPacket, Hostman, UltaHost, IShosting and AEserver. You choose the server, we deploy and maintain it.'),
 'keysy.html': ('Кейсы MakeBiz: внедрение CRM Битрикс24, AI-агентов и аналитики',
   None),
 'en/keysy.html': ('MakeBiz case studies: Bitrix24 CRM, AI agents and analytics',
   None),
 'news.html': ('Новости MakeBiz: AI-агенты, CRM и автоматизация бизнеса',
   'Разборы и новости про AI-агентов, искусственный интеллект, CRM, продажи и автоматизацию бизнеса: коротко, по делу и с примерами из проектов MakeBiz.'),
 'en/news.html': ('MakeBiz News: AI agents, CRM and business automation',
   'Analysis and news about AI agents, artificial intelligence, CRM, sales and business automation: short, practical, with examples from MakeBiz projects.'),
 'contacts.html': ('Контакты MakeBiz Group в Дубае: Telegram, WhatsApp, заявка',
   None),
 'en/contacts.html': ('Contact MakeBiz Group in Dubai: Telegram, WhatsApp, request',
   None),
 'calculator-agents.html': ('Калькулятор стоимости AI-агентов для бизнеса | MakeBiz',
   'Соберите команду AI-агентов из каталога и сразу увидите цену внедрения и обслуживания в AED. Тарифы Старт, Бизнес и Холдинг, внедрение от 6 000 AED.'),
 'en/calculator-agents.html': ('AI agents cost calculator for business | MakeBiz',
   'Build your team of AI agents from the catalogue and see the implementation and support price in AED at once. Start, Business and Holding plans, from AED 6,000.'),
 'partners.html': (None,
   'Партнёрская программа MakeBiz Group: 20% с первой оплаты клиента и 10% весь следующий год за рекомендации на AI-агентов, Битрикс24, Vector и IntDoc.'),
 'en/partners.html': (None,
   'MakeBiz Group partner programme: 20% of the first client payment and 10% for the following year for referrals to AI agents, Bitrix24, Vector and IntDoc.'),
 'privacy.html': (None,
   'Как MakeBiz собирает, использует и защищает персональные данные посетителей сайта: какие данные, зачем, правовые основания, cookie, третьи лица и ваши права.'),
 'en/privacy.html': (None,
   'How MakeBiz collects, uses and protects the personal data of website visitors: what data, why, legal basis, cookies, third parties, storage and your rights.'),
}

# Грамматика английских заголовков (исходный HTML страницы или шаблона бандла)
EN_FIX = {
 'en/contacts.html': [
   ('<h1>We are always ready discuss your project</h1>', '<h1>We are always ready to discuss your project</h1>'),
   ('TPL:We are always ready <span style="background:linear-gradient(115deg,#48F58C,#12B857);-webkit-background-clip:text;background-clip:text;color:transparent;">discuss your project</span>',
    'We are always ready <span style="background:linear-gradient(115deg,#48F58C,#12B857);-webkit-background-clip:text;background-clip:text;color:transparent;">to discuss your project</span>')],
 'en/index.html': [
   ('<h2>Four products, that reinforce each other</h2>', '<h2>Four products that reinforce each other</h2>'),
   ('TPL:Four products, <span style="color:#16C15A;">that reinforce each other</span>', 'Four products <span style="color:#16C15A;">that reinforce each other</span>')],
 'en/vector.html': [
   ('Why business loses customers, <span style="color:#E4384D;">even if there are many calls</span>', 'Why businesses lose customers <span style="color:#E4384D;">even when there are plenty of calls</span>'),
   ('Oversight of calls and employees <span style="color:#16C15A;">and growth points in one place</span>', 'Calls, employees <span style="color:#16C15A;">and growth points in one place</span>'),
   ('What you get <span style="color:#16C15A;">business and team</span>', 'What the <span style="color:#16C15A;">business and the team</span> get'),
   ('Not control for the sake of control, <span style="color:#16C15A;">and a sales growth system</span>', 'Not control for the sake of control, <span style="color:#16C15A;">but a sales growth system</span>'),
   ('How to start quickly and see right away, <span style="color:#16C15A;">where sales are lost</span>', 'How to start fast and see right away <span style="color:#16C15A;">where sales are lost</span>'),
   ('Choose a plan for your volume <span style="color:#16C15A;">your department calls</span>', 'Choose a plan for <span style="color:#16C15A;">your call volume</span>'),
   ('Connect Vector and see, <span style="color:#16C15A;">where the department loses customers</span>', 'Connect Vector and see <span style="color:#16C15A;">where your team loses customers</span>'),
   ('>What happened with the client</h3>', '>What happened to the client</h3>'),
   ('>Whether it leads to a deal</h3>', '>Does it lead to a deal</h3>')],
 'en/intdoc.html': [
   ('What IntDoc does <span class="grad">sees in the document</span>', 'What IntDoc <span class="grad">sees in a document</span>'),
   ('What you get <span class="grad">a procurement team in the UAE</span>', 'What <span class="grad">a procurement team in the UAE</span> gets'),
   ('Not a spreadsheet in Excel, <span class="grad">and the purchasing decision</span>', 'Not an Excel spreadsheet, <span class="grad">but a purchasing decision</span>')],
 'en/vps.html': [
   ('What makes it strong <span style="color:#1FDB6D;">each platform</span>', 'What <span style="color:#1FDB6D;">each platform</span> does best'),
   ('You take the server yourself, <span style="color:#1FDB6D;">and we will deploy and maintain it</span>', 'You choose the server, <span style="color:#1FDB6D;">we deploy and maintain it</span>')],
 'en/news.html': [
   ('About AI and agents <span class="g">and business without the routine</span>', 'About AI, agents <span class="g">and business without the routine</span>')],
}
