#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Разводит длинные тексты кейсов (проблема, решение, результат) с makebiz.life.

Карточки кейсов развели раньше (diverge_cases.py), а эти три поля видны на самих
страницах кейсов и совпадали с российским сайтом дословно. Факты те же, формулировки
другие: цифры, названия и сроки не меняем.

Правим и данные (cases-data.js), и собранные страницы кейсов: build_c1 печёт их из
снимка браузера, а Playwright на Маке нет.

    python3 .seo/uae/diverge_cases_long.py .
"""
import glob, io, os, sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'
os.chdir(ROOT)

PAIRS_RU = [
 ('Апартика сдаёт квартиры, апартаменты, дачи и дома по всей России, и объектов больше тысячи. Объявления нужно размещать и держать в актуальном виде сразу на многих площадках, заявки идут потоком с Avito, Циан и других сайтов, из мессенджеров и по телефону, а дальше их надо квалифицировать, брать в бронирование, подтверждать и собирать обратную связь. Пока всё это велось вручную и в разных местах, объявления и заявки терялись, менеджеры тонули в рутине, а единой картины по объектам, броням и качеству работы не было.',
  'У Апартики больше тысячи объектов по всей России: квартиры, апартаменты, дачи и дома. Каждое объявление надо разместить сразу на нескольких площадках и держать актуальным, а заявки валятся потоком с Avito, Циан, из мессенджеров и по телефону, и каждую надо квалифицировать, довести до брони, подтвердить и потом собрать обратную связь. Пока это жило в разных местах и делалось руками, объявления и заявки терялись, менеджеры сидели в рутине, а общей картины по объектам, броням и качеству сервиса не было ни у кого.'),
 ('Внедрили CRM под аренду недвижимости и связали её со всем внешним контуром. Настроили автоматический постинг объявлений на Avito, Циан и другие площадки и обратную загрузку: все обращения с площадок, сайта, мессенджеров и телефонии падают прямо в CRM с привязкой к объекту. Первичную обработку и квалификацию заявок взял на себя AI-агент: он отвечает мгновенно, уточняет даты, параметры и бюджет, подбирает подходящие объекты и передаёт горячие заявки менеджеру. Менеджеры ведут всё в CRM, а агент помогает на каждом шаге: в бронировании, подтверждении брони и сборе обратной связи после заселения. Подключили BI-дашборды, чтобы команда видела свои показатели по объектам, площадкам, заявкам и бронированиям. Отдельно внедрили речевую аналитику Vector: она разбирает звонки операторов и клиентов и оценивает, насколько сотрудники доброжелательны, вежливы и эмпатичны, чтобы держать сервис на уровне. Решение работает одинаково для всех типов объектов и по всем регионам страны.',
  'Поставили CRM под аренду и связали её со всем внешним контуром. Объявления уходят на Avito, Циан и другие площадки автоматически, а обратно в CRM падают все обращения с площадок, сайта, мессенджеров и телефонии, сразу привязанные к объекту. Первый ответ и квалификацию забрал на себя AI-агент: отвечает мгновенно, уточняет даты, параметры и бюджет, подбирает подходящие варианты и отдаёт горячие заявки менеджеру. Менеджер ведёт всё в CRM, агент подставляется на каждом шаге: бронь, подтверждение, обратная связь после заселения. Сверху BI-дашборды по объектам, площадкам, заявкам и бронированиям. Отдельно поставили речевую аналитику Vector: она разбирает разговоры операторов с клиентами и оценивает, насколько сотрудник доброжелателен, вежлив и эмпатичен. Схема работает одинаково и для квартиры в городе, и для дома за городом, в любом регионе.'),
 ('Теперь вся аренда живёт в одной CRM: объявления публикуются на площадках автоматически, заявки со всех источников собираются и квалифицируются агентом, брони, подтверждения и обратная связь ведутся в системе, а руководство видит показатели по объектам и площадкам в дашбордах. Vector показывает, как команда говорит с клиентами, и держит вежливость и эмпатию под контролем. Процесс одинаково работает и на квартиру в городе, и на дом за городом, по всей стране.',
  'Аренда целиком живёт в одной CRM: объявления публикуются сами, заявки со всех источников собираются и проходят через агента, брони, подтверждения и обратная связь ведутся в системе, а руководство смотрит на объекты и площадки в дашбордах. Vector показывает, как команда разговаривает с клиентами, и держит вежливость под контролем. Один и тот же процесс работает по всей стране, на любом типе объекта.'),

 ('У Unilin большая сеть региональных и разъездных менеджеров, которые работают в полях: торговые точки, дилеры и партнёры по всей стране. Данные о визитах, точках и продажах оседали в разрозненных таблицах и на местах, коробочная CRM в базовом виде не покрывала их процессы, а руководство не видело единой картины по рынку, точкам и продуктам. Нужна была система, в которой менеджер в разъездах работает так же удобно, как из офиса.',
  'Сеть региональных и разъездных менеджеров Unilin работает в полях: торговые точки, дилеры и партнёры по всей стране. Визиты, точки и продажи оседали в таблицах и на местах, коробка CRM в базовом виде их процессы не закрывала, а у руководства не складывалась картина по рынку, точкам и продуктам. Нужна была система, в которой человек в разъезде работает не хуже, чем из офиса.'),
 ('Развернули и глубоко доработали коробочный Битрикс24 на сервере клиента под их процессы. Настроили бизнес-процессы и работу разъездных менеджеров прямо из мобильного приложения: визиты в торговые точки, задачи, сделки и отчёты с телефона в полях. Сделали кастомную доработку коробочной версии под региональные продажи и сопровождаем её третий год. Построили сквозные интеграции с 1С и ERP, чтобы номенклатура, отгрузки и данные ходили между системами без ручного переноса. Собрали BI-дашборды с аналитикой по нескольким срезам: аналитика рынка, аналитика по торговым точкам, аналитика по продуктам и аналитика по компании в целом.',
  'Развернули коробочный Битрикс24 на сервере клиента и глубоко доработали под их процессы. Настроили бизнес-процессы и работу разъездных менеджеров прямо с мобильного: визиты в торговые точки, задачи, сделки и отчёты с телефона в полях. Коробку доработали кастомно под региональные продажи и сопровождаем её третий год. Построили сквозные интеграции с 1С и ERP, чтобы номенклатура, отгрузки и данные ходили между системами без ручного переноса. Собрали BI-дашборды по четырём срезам: рынок, торговые точки, продукты и компания целиком.'),
 ('Теперь разъездные менеджеры ведут регионы и торговые точки прямо с телефона, а данные сразу попадают в единую систему. Руководство видит рынок, точки, продукты и компанию в дашбордах, коробка Битрикс24 доработана под реальные процессы Unilin, а связка с 1С и ERP держит данные в одном контуре. Идёт третий год развития и поддержки.',
  'Разъездные менеджеры ведут регионы и торговые точки с телефона, данные сразу попадают в общую систему. Руководство смотрит рынок, точки, продукты и компанию в дашбордах, коробка доработана под реальные процессы Unilin, а связка с 1С и ERP держит данные в одном контуре. Идёт третий год развития и поддержки.'),

 ('У СДЭК большое корпоративное направление и филиалы в России и Казахстане, а работа с B2B-клиентами шла в разных системах и во многом вручную. Стандартная коробка CRM не покрывала их процессы, обращения вне рабочего времени и рутина менеджеров тормозили ведение клиентов, а единой аналитики по корпоративным клиентам не было.',
  'Корпоративное направление СДЭК большое, филиалы в России и Казахстане, а работа с B2B-клиентами была размазана по разным системам и во многом делалась руками. Стандартная коробка CRM процессы не закрывала, обращения вне рабочего времени висели, менеджеры тонули в рутине, а единой аналитики по корпоративным клиентам не существовало.'),
 ('Внедрили и глубоко доработали коробочный Битрикс24 под работу с корпоративными клиентами по филиалам России и Казахстана: ведение, отслеживание, поддержка и аккаунтинг. Сделали сквозные интеграции с их внутренней CRM, внутренними системами и ресурсами, телефонией и мессенджерами. Собрали набор AI-агентов: один отвечает во внерабочее время, второй квалифицирует лиды, третий разбирает входящую почту, четвёртый помогает менеджерам, пятый ведёт задачи и сроки. Подключили BI-дашборды со сквозной аналитикой по корпоративным клиентам.',
  'Внедрили коробочный Битрикс24 и глубоко доработали его под работу с корпоративными клиентами по филиалам России и Казахстана: ведение, отслеживание, поддержка и аккаунтинг. Сделали сквозные интеграции с их внутренней CRM, внутренними системами, телефонией и мессенджерами. Собрали набор AI-агентов: первый отвечает во внерабочее время, второй квалифицирует лиды, третий разбирает входящую почту, четвёртый помогает менеджерам, пятый ведёт задачи и сроки. Подключили BI-дашборды со сквозной аналитикой по корпоративным клиентам.'),
 ('Теперь корпоративная команда СДЭК работает в едином контуре: каждый клиент ведётся, отслеживается и поддерживается в одном месте, агенты закрывают рутину и внерабочее время, а руководство видит корпоративных клиентов в дашбордах. Идёт второй год сотрудничества.',
  'Корпоративная команда СДЭК работает в одном контуре: клиент ведётся, отслеживается и поддерживается в одном месте, агенты закрывают рутину и ночные обращения, а руководство видит корпоративных клиентов в дашбордах. Идёт второй год сотрудничества.'),

 ('У HAVAL сеть автосалонов по всей России и огромный поток звонков по продажам, больше 300 000 минут разговоров в месяц даже по выборке. Проверить такой объём вручную невозможно, выборочный контроль охватывал доли процента, а готовые сервисы с такими объёмами и с 40+ критериями общения не справлялись. Из-за этого отклонения от скриптов и упущенные продажи оставались незамеченными.',
  'Сеть автосалонов HAVAL по всей России даёт огромный поток звонков по продажам: больше 300 000 минут разговоров в месяц даже по выборке. Вручную такой объём не проверить, выборочный контроль дотягивался до долей процента, а готовые сервисы не тянули ни объём, ни 40+ критериев общения. Отклонения от скриптов и упущенные продажи оставались незамеченными.'),
 ('Внедрили речевую аналитику Vector как полностью кастомную разработку: система разбирает звонки по всей сети и оценивает каждый разговор по 40+ критериям на базе чек-листа и скриптов, обрабатывая более 300 000 минут в месяц. AI-агенты подсвечивают слабые звонки: если разговор опускается ниже 70%, он автоматически эскалируется на старшего менеджера, чтобы не потерять продажу. Подключили BI-дашборды с глубокой аналитикой влияния звонков на продажи и отслеживанием сделок после звонка, сбор NPS и обратной связи, и отдаём руководству готовые выжимки. Речевая аналитика, агенты и дашборды сделаны под ключ. Дополнительно агенты записывают клиентов в автосервис, напоминают о плановом ТО и допродажах и ведут их как аккаунт-менеджеры.',
  'Речевую аналитику Vector сделали полностью кастомной разработкой: система разбирает звонки по всей сети и оценивает каждый разговор по 40+ критериям на базе чек-листа и скриптов, обрабатывая больше 300 000 минут в месяц. AI-агенты подсвечивают слабые звонки: разговор ниже 70% автоматически уходит на старшего менеджера, чтобы не потерять продажу. Подключили BI-дашборды с аналитикой влияния звонков на продажи, отслеживанием сделок после звонка, сбором NPS и обратной связи, а руководству отдаём готовые выжимки. Аналитика, агенты и дашборды сделаны под ключ. Дополнительно агенты записывают клиентов в автосервис, напоминают о плановом ТО и допродажах и ведут их как аккаунт-менеджеры.'),
 ('Теперь HAVAL видит, как вся сеть говорит с клиентами, на объёме, недоступном ни ручному контролю, ни готовым сервисам. Слабые звонки ловятся и эскалируются вовремя, соблюдение скриптов измеримо, а связь звонка и продажи видна в дашбордах, а не на глаз.',
  'HAVAL видит, как вся сеть разговаривает с клиентами, на объёме, который не берут ни ручной контроль, ни готовые сервисы. Слабые звонки ловятся и уходят наверх вовремя, соблюдение скриптов измеримо, а связь звонка и продажи видна в дашбордах, а не на глаз.'),

 ('У компании много программ обучения и подбора персонала, пять юридических лиц и расчёты в разных валютах. Продажи, выдача курсов, аккаунтинг и финансы велись в разных местах и во многом вручную, поэтому трудно было контролировать оплаты и рассрочки, вовремя запускать учебные группы и видеть общую картину по клиенту и деньгам.',
  'У компании много программ обучения и подбора персонала, пять юридических лиц и расчёты в нескольких валютах. Продажи, выдача курсов, аккаунтинг и финансы жили в разных местах и во многом делались руками, поэтому оплаты и рассрочки было трудно контролировать, учебные группы запускались с задержкой, а общей картины по клиенту и деньгам не складывалось.'),
 ('Теперь весь путь от заявки до выпуска группы и закрытия оплат живёт в одной системе. Оплаты, рассрочки и задолженности под контролем, учебные группы запускаются по чек-листам, а руководитель видит клиента, продажи, лиды и деньги в BI-дашборде, а не в разрозненных таблицах.',
  'Путь от заявки до выпуска группы и закрытия оплат живёт в одной системе. Оплаты, рассрочки и задолженности под контролем, учебные группы запускаются по чек-листам, а руководитель видит клиента, продажи, лиды и деньги в BI-дашборде, а не в разрозненных таблицах.'),
]

PAIRS_RU.append(
 ('Внедрили Битрикс24 под весь цикл. Настроили базу на пять юридических лиц и четыре валюты, две линии продаж с квалификацией и контролем оплат, передачу в предоставление и воронку выпуска учебных групп с посещаемостью и опросами по всем программам, включая ПЭН и Консультирование. Добавили аккаунтинг и апсейл, финансовые смарт-процессы: рассрочки, дебиторку и кредиторку, документооборот через СБИС и 20 шаблонов документов для финслужбы. Собрали BI-дашборд со сквозной аналитикой: все показатели в одном окне, по продуктам, продажам, лидам и поведению клиентов, с графиками для руководителя. Провели обучение по ролям и месяц сопровождали запуск.',
  'Внедрили Битрикс24 на весь цикл. Настроили базу на пять юрлиц и четыре валюты, две линии продаж с квалификацией и контролем оплат, передачу в предоставление и воронку выпуска учебных групп с посещаемостью и опросами по всем программам, включая ПЭН и Консультирование. Добавили аккаунтинг и апсейл, финансовые смарт-процессы: рассрочки, дебиторку и кредиторку, документооборот через СБИС и 20 шаблонов документов для финслужбы. Собрали BI-дашборд со сквозной аналитикой: показатели в одном окне по продуктам, продажам, лидам и поведению клиентов, с графиками для руководителя. Провели обучение по ролям и месяц сопровождали запуск.'))

PAIRS_EN = [
 ('Apartico rents out apartments, serviced apartments, dachas and houses across Russia, with over a thousand objects. Listings have to be posted and kept current on many portals at once, enquiries pour in from Avito, Cian and other sites, from messengers and by phone, and then they have to be qualified, taken into booking, confirmed and followed up for feedback. While all of this was done by hand and in different places, listings and enquiries got lost, managers drowned in routine, and there was no single picture of objects, bookings and service quality.',
  'Apartico has over a thousand objects across Russia: apartments, serviced apartments, dachas and houses. Every listing has to go out to several portals at once and stay current, while enquiries pour in from Avito, Cian, messengers and the phone, and each one has to be qualified, turned into a booking, confirmed and followed up for feedback. As long as that lived in different places and ran on manual work, listings and enquiries slipped through, managers sat in routine, and nobody had a single picture of objects, bookings and service quality.'),
 ('We rolled out a CRM for property rental and tied it to the whole external loop. We set up automatic posting of listings to Avito, Cian and other portals and a reverse feed: every enquiry from portals, the website, messengers and telephony lands straight in the CRM linked to its object. First response and qualification were taken over by an AI agent: it replies instantly, clarifies dates, parameters and budget, suggests suitable objects and passes hot enquiries to a manager. Managers run everything in the CRM, and the agent helps at every step: booking, booking confirmation and feedback collection after check in. We connected BI dashboards so the team sees its metrics by object, portal, enquiry and booking. Separately we deployed Vector speech analytics: it processes operator and client calls and scores how friendly, polite and empathetic the staff are, to keep service at a high level. The solution works the same for every object type and across all regions of the country.',
  'We put in a rental CRM and wired it to the whole external loop. Listings go out to Avito, Cian and other portals on their own, and every enquiry from portals, the website, messengers and telephony comes back into the CRM already linked to its object. An AI agent took over the first reply and the qualification: it answers instantly, checks dates, parameters and budget, suggests matching options and hands hot enquiries to a manager. The manager runs everything in the CRM while the agent steps in at every point: the booking, the confirmation, the feedback after check in. On top sit BI dashboards by object, portal, enquiry and booking. Vector speech analytics went in separately: it goes through operator conversations with clients and scores how friendly, polite and empathetic the person was. The same scheme works for a city apartment and for a house out of town, in any region.'),
 ('Now the whole rental business lives in one CRM: listings are published to portals automatically, enquiries from every source are collected and qualified by the agent, bookings, confirmations and feedback are run in the system, and management sees the metrics by object and portal in dashboards. Vector shows how the team talks to clients and keeps politeness and empathy under control. The same process works for a city apartment and a house in the countryside, across the whole country.',
  'The rental business now sits entirely in one CRM: listings publish themselves, enquiries from every source are collected and go through the agent, bookings, confirmations and feedback are run in the system, and management looks at objects and portals in dashboards. Vector shows how the team speaks to clients and keeps politeness in check. One and the same process runs across the country, on any type of object.'),

 ('Unilin has a large network of regional and field managers who work on the road: retail points, dealers and partners across the country. Data on visits, points and sales was scattered across spreadsheets and local files, the boxed CRM out of the box did not cover their processes, and management had no single picture of the market, points and products. They needed a system where a manager on the road works as comfortably as from the office.',
  'The Unilin network of regional and field managers works on the road: retail points, dealers and partners across the country. Visits, points and sales settled into spreadsheets and local files, an out of the box CRM did not close their processes, and management never got a picture of the market, the points and the products. They needed a system where somebody on the road works no worse than from the office.'),
 ('We deployed and deeply customized the on-premise Bitrix24 on the client server for their processes. We set up business processes and field manager work straight from the mobile app: visits to retail points, tasks, deals and reports from a phone in the field. We custom developed the boxed version for regional sales and have supported it for a third year. We built end to end integrations with 1C and ERP so that catalogue, shipments and data move between systems without manual transfer. We assembled BI dashboards with analytics across several cuts: market analytics, retail point analytics, product analytics and company wide analytics.',
  'We deployed the on-premise Bitrix24 on the client server and reworked it deeply for their processes. Business processes and field manager work were set up straight from mobile: visits to retail points, tasks, deals and reports from a phone out in the field. The boxed version was custom built for regional sales and we have supported it for a third year. End to end integrations with 1C and ERP move catalogue, shipments and data between systems with no manual transfer. BI dashboards cover four cuts: the market, retail points, products and the company as a whole.'),
 ('Now field managers run regions and retail points straight from a phone, and the data lands in a single system at once. Management sees the market, points, products and the company in dashboards, the boxed Bitrix24 is customized to Unilin real processes, and the link with 1C and ERP keeps data in one loop. This is the third year of development and support.',
  'Field managers run regions and retail points from a phone, and the data lands in the shared system straight away. Management looks at the market, points, products and the company in dashboards, the boxed Bitrix24 fits the real Unilin processes, and the link with 1C and ERP keeps data in one loop. This is the third year of development and support.'),

 ('CDEK has a large corporate direction and branches in Russia and Kazakhstan, and work with B2B clients was spread across different systems and largely manual. The standard boxed CRM did not cover their processes, after hours requests and manager routine slowed client management down, and there was no unified analytics on corporate clients.',
  'The CDEK corporate arm is large, with branches in Russia and Kazakhstan, and work with B2B clients was smeared across different systems and largely done by hand. A standard boxed CRM did not close the processes, after hours requests hung unanswered, managers drowned in routine, and unified analytics on corporate clients did not exist at all.'),
 ('We deployed and heavily customized the on-premise Bitrix24 for corporate client work across branches in Russia and Kazakhstan: management, tracking, support and account management. We built end to end integrations with their internal CRM, internal systems and resources, telephony and messengers. We assembled a set of AI agents: one answers after hours, one qualifies leads, one parses incoming email, one assists managers, and one keeps tasks and deadlines moving. We connected BI dashboards with end to end analytics on corporate clients.',
  'We put in the on-premise Bitrix24 and reworked it heavily for corporate client work across the branches in Russia and Kazakhstan: management, tracking, support and account management. End to end integrations tie it to their internal CRM, internal systems, telephony and messengers. A set of AI agents went in: the first answers after hours, the second qualifies leads, the third parses incoming email, the fourth assists managers, the fifth keeps tasks and deadlines moving. BI dashboards give end to end analytics on corporate clients.'),
 ('Now the CDEK corporate team works in one loop: every client is managed, tracked and supported in one place, agents cover routine and after hours, and management sees corporate clients in dashboards. This is the second year of the partnership.',
  'The CDEK corporate team works in one loop: a client is managed, tracked and supported in one place, agents cover the routine and the night requests, and management sees corporate clients in dashboards. This is the second year of the partnership.'),

 ('HAVAL has a dealership network across Russia and a huge flow of sales calls, over 300,000 minutes of conversation a month even on a sample. Checking that volume by hand is impossible, spot checks covered a fraction of a percent, and off the shelf tools could not cope with such volumes and 40+ communication criteria. Script deviations and lost sales went unnoticed.',
  'The HAVAL dealership network across Russia produces a huge flow of sales calls: over 300,000 minutes of conversation a month even on a sample. That volume cannot be checked by hand, spot checks reached a fraction of a percent, and off the shelf tools handled neither the volume nor 40+ communication criteria. Script deviations and lost sales went unnoticed.'),
 ('We built Vector speech analytics as a fully custom solution: it processes calls across the whole network and scores every conversation against 40+ criteria based on a checklist and scripts, handling over 300,000 minutes a month. AI agents flag weak calls: if a conversation drops below 70%, it is automatically escalated to a senior manager so the sale is not lost. We connected BI dashboards with deep analytics on how calls influence sales and tracking of deals after a call, NPS and feedback collection, and we give management ready summaries. The speech analytics, the agents and the dashboards are all custom development. On top of that, agents book customers into the service center, remind about scheduled maintenance and upsells, and act as account managers.',
  'Vector speech analytics was built as fully custom development: it goes through calls across the whole network and scores every conversation against 40+ criteria drawn from a checklist and the scripts, handling over 300,000 minutes a month. AI agents flag the weak calls: a conversation under 70% is pushed to a senior manager automatically so the sale is not lost. BI dashboards cover how calls influence sales, track deals after a call, collect NPS and feedback, and management gets ready summaries. The analytics, the agents and the dashboards are all custom work. On top of that the agents book customers into the service centre, remind them about scheduled maintenance and upsells, and act as account managers.'),
 ('Now HAVAL sees how the whole network talks to customers, at a scale beyond manual review or off the shelf tools. Weak calls are caught and escalated in time, script compliance is measurable, and the link between a call and a sale is visible in dashboards rather than guessed.',
  'HAVAL sees how the whole network speaks to customers, at a scale neither manual review nor off the shelf tools can take. Weak calls are caught and pushed up in time, script compliance is measurable, and the link between a call and a sale shows up in dashboards instead of being guessed.'),

 ('The company runs many training and recruitment programs, has five legal entities and settles in several currencies. Sales, course delivery, account management and finance were kept in different places and largely by hand, so it was hard to control payments and installments, launch training groups on time, and see the full picture of a client and the money.',
  'The company runs a lot of training and recruitment programmes, holds five legal entities and settles in several currencies. Sales, course delivery, account management and finance lived in different places and largely ran on manual work, so payments and installments were hard to control, training groups launched late, and the full picture of a client and the money never came together.'),
 ('We rolled out Bitrix24 for the whole cycle. We set up the base for five legal entities and four currencies, two sales lines with qualification and payment control, handoff to delivery and a training-group funnel with attendance and surveys across all their programs and consulting. We added account management and upsell, finance smart-processes (installments, receivables and payables), electronic document flow, and 20 document templates for the finance team. We built a BI dashboard with end to end analytics: every metric in one window, by product, sales, leads and customer behavior, with charts for management. We trained the team by role and supported the launch for a month.',
  'We rolled Bitrix24 out across the whole cycle. The base was set up for five legal entities and four currencies, with two sales lines carrying qualification and payment control, a handoff into delivery and a training-group funnel with attendance and surveys across every programme and consulting. We added account management and upsell, finance smart-processes (installments, receivables and payables), electronic document flow and 20 document templates for the finance team. A BI dashboard brings the metrics into one window by product, sales, leads and customer behaviour, with charts for management. We trained the team by role and stayed with the launch for a month.'),
 ('Now the whole path from enquiry to a graduated group and closed payments lives in one system. Payments, installments and debts are under control, training groups launch by checklist, and the manager sees the client, sales, leads and money in a BI dashboard rather than scattered spreadsheets.',
  'The path from enquiry to a graduated group and closed payments lives in one system. Payments, installments and debts are under control, training groups launch by checklist, and the manager sees the client, sales, leads and money in a BI dashboard instead of scattered spreadsheets.'),
]

def patch(path, pairs):
    h = io.open(path, encoding='utf-8').read()
    before = h
    done = skipped = 0
    for old, new in pairs:
        assert old not in new, 'новая строка не должна содержать старую: %s' % old[:50]
        if old not in h and old.endswith('.'):
            # на собранных страницах точка в конце абзаца снята модулем чистки,
            # поэтому там текст лежит без неё
            old, new = old[:-1], new[:-1] if new.endswith('.') else new
        if old not in h:
            skipped += 1
            continue
        h = h.replace(old, new)
        done += 1
    if h != before:
        io.open(path, 'w', encoding='utf-8').write(h)
    print('%s: заменено %d, уже было %d' % (path, done, skipped))


def main():
    patch('keysy/cases-data.js', PAIRS_RU)
    patch('en/keysy/cases-data.js', PAIRS_EN)
    for f in sorted(glob.glob('keysy/*.html')) + ['keysy.html']:
        patch(f, PAIRS_RU)
    for f in sorted(glob.glob('en/keysy/*.html')) + ['en/keysy.html']:
        patch(f, PAIRS_EN)


if __name__ == '__main__':
    main()
